### PR TITLE
Build Page QoL changes

### PR DESCRIPTION
**Pull request by jimmyh77**
Search input has focus - (not 100% this is the best way of doing this)
Added an option to only show positive tile modifiers
Added colour theme options for the tile modifier overlay colour scale.

### CODE REVIEW

**Comment by jimmyh77** [comment]
Not sure if I've missed something.  But with the new options I've added for colours, if I try to reset a single colour and save, it reverts back to the colour which I've picked.  Only a reset all reverts the colours

**Comment by jimmyh77** [comment]
> Not sure if I've missed something. But with the new options I've added for colours, if I try to reset a single colour and save, it reverts back to the colour which I've picked. Only a reset all reverts the colours

Never mind.  It's doing it on live as well.   I'll see if I can find the cause and fix.

**Comment by insraq** [comment]
I have merged this but I reimplement the show positive modifiers. It's better to keep the checkbox there always because showing the checkbox only on select will shift the page layout, which is not great.

I don't think focus is implemented correctly - I have removed that as well.

**Comment by jimmyh77** [comment]
> I have merged this but I reimplement the show positive modifiers. It's better to keep the checkbox there always because showing the checkbox only on select will shift the page layout, which is not great.
> 
> I don't think `focus` is implemented correctly - I have removed that as well.
> 
> See this: [261b761](https://github.com/fishpondstudio/IndustryIdle/commit/261b7612edbedb1c60a3a4cb574bc15fcd833288)
> 
> Also, it seems that files are not formatted correctly? My `prettier` seems to introduce formatting changes.

@insraq Would you mind explaining why shifting the page layout it not great?

For prettier, is that .prettierrc.json?

**Comment by insraq** [comment]
> Would you mind explaining why shifting the page layout it not great?

When you click the checkbox, the page layout will shift down, which means the cursor will point to the wrong position. If you click without moving the cursor, you would not uncheck the selected item - if you want to uncheck, you need to move your cursor down. This is not an ideal UX.

**Pull request merged**
