### PR TITLE
Copper 2x policy

### PR DESCRIPTION
**Pull request by jimmyh77**

### CODE REVIEW

**Comment by insraq** [comment]
Copper is not a common resource - i.e. it cannot be found on all maps. There should be not a x2 policy for these unique resources (same for Cr, Li, U, Ti, etc)

**Comment by jimmyh77** [comment]
> Copper is not a common resource - i.e. it cannot be found on all maps. There should be not a x2 policy for these unique resources (same for Cr, Li, U, Ti, etc). If this were to be added, the whole balance needs to be reviewed.

How about Oil or Nat Gas, they are not on all maps but have 2x polcies?

**Comment by insraq** [comment]
They are fuel.

https://github.com/fishpondstudio/IndustryIdle/blob/1b7b477490f9db2aed93d643786f5e085773a5aa/assets/Script/CoreGame/MapDefinitions.ts#L36

Here, resources fall into 3 groups: first one is common resource (they should all have x2 policy), the second one is fuel resource (a map should in general have at least one, they all have x2 policy). the third one is rare resources - most maps have 1-2, they do not have x2 policy

**Comment by jimmyh77** [comment]
Ok, when you explain it like that, I guess it makes sense.   I'll close the PR.

**Pull request closed without merging**
